version: 0.8.1.{build}
clone_folder: C:\dev\miam-player

init:
  - set vcarch=%arch%
  - if "%arch%" == "x64" set vcarch=amd64
  - if not %cc%==MinGW call "C:\Program Files (x86)\Microsoft Visual Studio %toolchain_version%.0\VC\vcvarsall.bat" %vcarch%
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - echo QTDIR=%QTDIR%

environment:
  matrix:
  - arch: x64
    cc: VS2015
    qt: 5.7
    toolchain_version: 14
    mode: release
    QTDIR: C:\Qt\5.7\msvc2015_64

install:
  - cmd: set PATH=%PATH%;%QTDIR%\bin
  - mkdir build
  - cd build

cache:
  - MIAM

before_build:
  - set PATH=%QTDIR%\bin;%PATH%
  - if %cc%==MinGW set PATH=C:\Qt\Tools\mingw%toolchain_version%_32\bin;%PATH%
  - echo PATH=%PATH%

build_script:
  - ..\tools\ci\win\build.bat

test: off
